name: Fetch JAKIM Prayer Times (Daily, MYT 00:00)

on:
  # 16:00 UTC daily === 00:00 MYT next day
  schedule:
    - cron: "0 16 * * *"
  workflow_dispatch: {}

permissions:
  contents: write

env:
  ZONE: SGR01          # change if needed
  PERIOD: month        # keep 'month' so the same monthly CSV gets refreshed nightly
  OUTDIR: data
  PYTHON_VERSION: "3.11"

jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Ensure output directory
        run: mkdir -p "${{ env.OUTDIR }}"

      - name: Fetch (refresh this month's CSV)
        run: |
          python fetch_prayer_times.py --zone "${{ env.ZONE }}" --period "${{ env.PERIOD }}" --outdir "${{ env.OUTDIR }}"

      - name: Commit CSV if changed
        run: |
          set -e
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if ! git diff --quiet -- "${{ env.OUTDIR }}/"; then
            git add "${{ env.OUTDIR }}/"
            git commit -m "chore: nightly refresh (MYT 00:00)"
            git push
          else
            echo "No changes to commit."
          fi
